Reenable Web Engine Widgets for Qt 6.8.3
- The downloads for Qt 6.8.3 do not provide
  [QtWebEngine](https://github.com/Vertexwahn/rules_qt6/issues/39),
  but they are provided for Qt 6.4.0.
- However, even when configuring for version 6.4.0 in my `MODULE.bazel`,
  I would get an error message:

```
ERROR: /home/clemens-zangl/Documents/Projects/notepadqq/src/ui/BUILD.bazel:319:14: no such target '@@rules_qt+//:qt_web_engine_widgets': target 'qt_web_engine_widgets' not declared in package '' defined by /home/clemens-zangl/.cache/bazel/_bazel_clemens-zangl/30e9dc012d04d265c4fe27266f59b6af/external/rules_qt+/BUILD.bazel and referenced by '//src/ui:editor'
```
- I therefore reenabled the configuration, even though the files
  are not available for Qt6.8.3.